/* This file is automatically generated by scripts/gen-syscall-list. Do not edit. */

/* All hooked syscalls */
#define HOOKED_SYSCALLS                                                                       \
    access, faccessat, faccessat2,                               /* access.c */               \
        chdir, chroot, chmod, fchmodat, chown, lchown, fchownat, /* chx.c */                  \
        uselib, execve, execveat,                                /* exec.c */                 \
        getdents, getdents64,                                    /* getdents.c */             \
        acct, quotactl,                                          /* kernel.c */               \
        kill, tkill, tgkill, pidfd_open,                         /* kill.c */                 \
        mount, umount2, move_mount, pivot_root, mount_setattr, statfs, sysfs,                 \
        fspick, /* mount.c */                                                                 \
        link, linkat, unlink, unlinkat, rename, renameat, renameat2, mkdir, mkdirat, mknod,   \
        mknodat, rmdir, name_to_handle_at,                                 /* name.c */       \
        open, openat, openat2, creat, truncate, open_tree,                 /* open.c */       \
        read, pread64, write, pwrite64, sendfile, copy_file_range, splice, /* read_write.c */ \
        stat, lstat, newfstatat, statx, readlink, readlinkat,              /* stat.c */       \
        swapon, swapoff,                                                   /* swap.c */       \
        utime, utimes, utimensat, futimesat,                               /* utimes.c */     \
        setxattr, lsetxattr, getxattr, lgetxattr, listxattr, llistxattr, removexattr,         \
        lremovexattr /* xattr.c */
