/* This file is automatically generated by scripts/gen-syscall-list. Do not edit. */

/* All hooked syscalls */
#define HOOKED_SYSCALLS                                                                          \
    link, linkat, unlink, unlinkat, rename, renameat, renameat2, mkdir, mkdirat, mknod, mknodat, \
        rmdir, name_to_handle_at,                                             /* name.c */       \
        acct, quotactl,                                                       /* kernel.c */     \
        mount, umount2, move_mount, pivot_root, mount_setattr, statfs, sysfs, /* mount.c */      \
        swapon, swapoff,                                                      /* swap.c */       \
        setxattr, lsetxattr, getxattr, lgetxattr, listxattr, llistxattr, removexattr,            \
        lremovexattr,                                            /* xattr.c */                   \
        getdents, getdents64,                                    /* getdents.c */                \
        open, openat, openat2, creat, truncate, open_tree,       /* open.c */                    \
        stat, lstat, newfstatat, statx, readlink, readlinkat,    /* stat.c */                    \
        access, faccessat, faccessat2,                           /* access.c */                  \
        kill,                                                    /* kill.c */                    \
        read, pread64, write, sendfile,                          /* read_write.c */              \
        chdir, chroot, chmod, fchmodat, chown, lchown, fchownat, /* chx.c */                     \
        uselib, execve, execveat,                                /* exec.c */                    \
        utime, utimes, utimensat, futimesat                      /* utimes.c */
